### PR TITLE
Fixes and improvements

### PR DESCRIPTION
**Pull request by GioviQ**

### CODE REVIEW

**Comment by GioviQ** [comment]
pull commits from base repository

**Comment by steveschmitt** [comment]
Thanks, I forgot all about this.  Will take a look.

**Comment by steveschmitt** [comment]
We didn't target `netstandard2.1` because it's not supported by .NET Framework.
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by marcelgood** [comment]
Hi @GioviQ. I see this has been sitting out there for a while. I just took a look, but there are like 22 commits in here with various things it seems, even some reverting of .NET standard. Can you please rebase your PR and squash your commits and remove what's no longer relevant?

**Comment by GioviQ** [comment]
This repository seems in fact abandoned, so I continued development by myself to make my fork working with blazor project https://github.com/enkodellc/blazorboilerplate/tree/development.
At this point I do not understand what to do for your project. What is no longer relevant? It all relevant to me.

**Comment by marcelgood** [comment]
What I meant is that your PR is behind the current master and consists of 22 individual commits which are hard to make sense of in the current context. If you squash your 22 commits down to 1 and then rebase it on the current master and resolve any merge conflicts, then we have a linear history and can better assess the changes you are proposing.

**Comment by GioviQ** [comment]
So do I have to close this PR and make another PR with a single commit right?

**Comment by marcelgood** [comment]
Yes, that's probably the easiest. Looks like your PR is directly from your fork's master. Normally, you would create a branch in your fork with all the changes you want, then create the PR from it, and once we merge it you would down merge the master to your fork. If you commit directly into your master's you'll be on a different timeline and it be difficult to get your changes into this repo. You'll probably have to rewind your history and get your master to where our master is, then branch from there and create the changes, squash them to a single commit and create a PR from your branch.

**Pull request closed without merging**
